DROP TABLE TASK2_OT;
CREATE TABLE TASK2_OT(
ORDER_ID TEXT,
ORDER_DATE DATE,
CUSTOMER_ID TEXT,
PRODUCT_ID VARCHAR(50),
CATEGORY VARCHAR(50),
SUB_CATEGORY VARCHAR(50),
PRODUCT_NAME TEXT,
SALES NUMERIC(10,2),
QUANTITY INT,
DISCOUNT NUMERIC(10,2),
PROFIT NUMERIC(10,2)
);

COPY TASK2_OT(ORDER_ID, ORDER_DATE, CUSTOMER_ID, PRODUCT_ID, CATEGORY, SUB_CATEGORY, PRODUCT_NAME, SALES, QUANTITY, DISCOUNT, PROFIT)
FROM 'C:\Maincraft Internship (14 April)\Task 2\Anushka_OT_Cleaned_Task2_Data.csv' 
DELIMITER ',' 
CSV HEADER 
QUOTE '"' 
ESCAPE '"';

SELECT * FROM TASK2_OT;

DROP TABLE TASK2_CT;
CREATE TABLE TASK2_CT(
CUSTOMER_ID TEXT,
CUSTOMER_NAME VARCHAR(100),
COUNTRY VARCHAR(50),
CITY VARCHAR(50),
STATE VARCHAR(50),
POSTAL_CODE INT,
REGION VARCHAR(50)
);

COPY TASK2_CT(CUSTOMER_ID, CUSTOMER_NAME, COUNTRY, CITY, STATE, POSTAL_CODE, REGION)
FROM 'C:\Maincraft Internship (14 April)\Task 2\Cleaned_CT_Task2_Data_Proper_Anushka.csv'
DELIMITER ','
CSV HEADER
QUOTE '"'
ESCAPE '"';

SELECT * FROM TASK2_CT;


--INNER JOIN
SELECT O.ORDER_ID, O.ORDER_DATE, O.CUSTOMER_ID, O.PRODUCT_ID, O.CATEGORY, O.SUB_CATEGORY, O.PRODUCT_NAME, O.SALES, O.QUANTITY, O.DISCOUNT, O.PROFIT,
       C.CUSTOMER_ID, C.CUSTOMER_NAME, C.COUNTRY, C.CITY, C.STATE, C.POSTAL_CODE, C.REGION
FROM TASK2_OT O
INNER JOIN
TASK2_CT C
ON O.CUSTOMER_ID= C.CUSTOMER_ID;

--TOTAL SALES BY REGION
SELECT C.REGION, SUM(O.SALES) AS TOTAL_SALES
FROM TASK2_CT C 
JOIN TASK2_OT O
ON C.CUSTOMER_ID=O.CUSTOMER_ID
GROUP BY C.REGION
ORDER BY TOTAL_SALES DESC;

--PROFIT MARGIN BY CATEGORY
SELECT CATEGORY, SUM(PROFIT)/SUM(SALES) AS PROFIT_MARGIN
FROM TASK2_OT
GROUP BY CATEGORY
ORDER BY PROFIT_MARGIN DESC;

--MONTHLY SALES TREND
SELECT
EXTRACT (MONTH FROM ORDER_DATE) AS MONTHS,
SUM(SALES) AS MONTHLY_SALES
FROM TASK2_OT
GROUP BY MONTHS
ORDER BY MONTHS;

--TOP 5 CUSTOMERS BY REVENUE
SELECT C.CUSTOMER_NAME, SUM(O.SALES) AS TOTAL_REVENUE
FROM TASK2_CT C
JOIN TASK2_OT O
ON C.CUSTOMER_ID=  O.CUSTOMER_ID
GROUP BY C.CUSTOMER_NAME
ORDER BY TOTAL_REVENUE DESC
LIMIT 5;